name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        Tell us about the feature you’d like to see.

  - type: textarea
    id: proposal
    attributes:
      label: Your proposal
      description: Describe the idea in detail
      placeholder: I would like to see...
    validations:
      required: true
