name: Allure Report with GitHub Comment

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests-with-allure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure_results

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure HTML report
        run: |
          allure generate allure_results --clean -o latest-report

      - name: Upload Allure HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: latest-report

      - name: Check for test failures
        id: check-failures
        run: |
          failed_count=$(grep -o '"status":"failed"' allure_results/*.json | wc -l)
          echo "failed_count=$failed_count" >> $GITHUB_ENV

      - name: Post comment if failures found
        if: env.failed_count != '0'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reportUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request ? context.payload.pull_request.number : context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ **Test Failures Detected**\n\nView full Allure report: [Allure Report Artifact](${reportUrl})`
            });
