name: Pytest with Allure Report

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure_results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1
        with:
          allure_results: allure_results

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Only deploy on main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true
